name: Run unit tests
on: push

env:
  JAVA_VERSION: 11

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}

      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: unitTests --info
